// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createNewLink = `-- name: CreateNewLink :one
INSERT INTO links (id, created_at, updated_at, code, link_url, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, code, link_url, user_id
`

type CreateNewLinkParams struct {
	Code    string
	LinkUrl string
	UserID  uuid.UUID
}

func (q *Queries) CreateNewLink(ctx context.Context, arg CreateNewLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createNewLink, arg.Code, arg.LinkUrl, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
		&i.LinkUrl,
		&i.UserID,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, created_at, updated_at, code, link_url, user_id FROM links WHERE code = $1
`

func (q *Queries) GetLink(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, code)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
		&i.LinkUrl,
		&i.UserID,
	)
	return i, err
}

const getNewLink = `-- name: GetNewLink :one
SELECT code FROM links WHERE user_id = $1 ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetNewLink(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getNewLink, userID)
	var code string
	err := row.Scan(&code)
	return code, err
}
